### ISSUE TITLE
IstioHeadersHolder Should be populated using Aspnet Core ModelBinding 

### ISSUE THREAD

**Issue by vpaulino** [nosinovacao/istio-tracing-aspnetcore#2]
Data that comes from Headers is populated with  databinding mechanism. IstioHeadersHolder  should also be populated the same way with some implementation of IModelBinder that is going to be selected by the [HeaderModelBinderProvider ](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/HeaderModelBinderProvider.cs)

**Comment by Symbianx** [comment]
Thank you for the suggestion 👍 
The library relies only on the Asp.Net Core middlewares and don't use any of the MVC classes.
I don't have much experience with Model Binding customization but as far as I know it is only available when using MVC, can you elaborate a bit more on how you plan to do this?

**Comment by vpaulino** [comment]
The fact that it brings the MVC is indeed a pain. If your requirement is to be lightweight then it would make no sense to bring that nugetpackage. Are you not considering to support MVC applications with this? only APIs ?

**Comment by Symbianx** [comment]
I'm not sure I understand where MVC fits into this library use case but since MVC relies on the Asp.Net Core middlewares pipeline it is already supported. 

All requests will hit our middleware before the MVC middleware, as we only use the middleware for extracting the header values it won't have any effect on the MVC request handling (or any other framework you may be using).

**Comment by vpaulino** [comment]
There is something called separation of concerns and Open to extension and closed to modification principles ( from SOLID definition ) and MVC Framework makes available a set of components that can be extended to add functionality regarding the functionality that you need. Middleware pipelines enable us to add steps to process the request and/or the response. Do you have the need to control/manipulate the request or the response to retrieve those header values ( it doesn't look that way) ? If you just want to read the values and binding them to some well known type then you should consider using the extensability points that the framework gives you to do that. Doing that, the binding is only executed if needed not processed to all requests that could impact when not needed.  

If you need to support this on any other framework, you should implement the functionality that you need to read from a dictionary a set of values and return an instance of your well know type separated from any type that is independent from any framework ( again... separation of concerns ). If in the nearest future you would want to support that on any other frameworks or communication protocols,  you will need to move code ( hopefully not doing any copy&paste ) ( DRY rule ) and need to generate a new nuget package to support all the worlds ( http, amqp, mqtt, or any other layers of communication between components that you may need to intercept to retrieve those values ).  

You should also consider separate in two different packages the client SDK and the Aspnet core Middleware SDK. those may have different development lifetime.   There  is no need client libraries have as dependencies to things as Microsoft.AspNetCore.*.

**Comment by Symbianx** [comment]
Although I appreciate a good SOLID, DRY and KISS discusssion, I don't think we need to add the dependency on the whole MVC framework just to extract 7 headers. 

We would effectively be replacing a [63 lines file](https://github.com/nosinovacao/istio-tracing-aspnetcore/blob/v1.0.0-alpha2/src/Istio.Tracing.Propagation.AspNetCore/IstioHeadersFetcherMiddleware.cs) with a binder of probably the same size new and a new (massive) dependency. We would also be reducing the potential users of this library by supporting only the MVC framework.

The scope of this library is to support [ISTIO distributed tracing, which specifies the headers for http only](https://istio.io/docs/tasks/telemetry/distributed-tracing/#understanding-what-happened), so *for now* I don't think we need to think about supporting more transport protocols.
