### ISSUE TITLE
Unable to resolve HttpContentAccessor

### ISSUE THREAD

**Issue by pedrojreis** [nosinovacao/istio-tracing-aspnetcore#3]
Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Istio.Tracing.Propagation.HeadersPropagationMessageHandlerBuilderFilter'

**Comment by Symbianx** [comment]
Thanks for the report 👍.

This happens because we expect the `IHttpContextAccessor` to be already registered in the IoC container.

You can workaround this issue it by adding the following line in the ConfigureServices method of the Startup.cs file:
`services.AddHttpContextAccessor();`
