### ISSUE TITLE
What about upgrading to 3.1 ?

### ISSUE THREAD

**Issue by alefcarlos** [nosinovacao/istio-tracing-aspnetcore#5]
What do you think upgrading this lib and releasing a new version on Nuget ?

**Comment by suvl** [comment]
@alefcarlos I'm not sure what you mean by that. This is a library, so it targets .net standard 2.0. We can look into targeting .net standard 2.1 but that won't change much so it's not that of a priority. When this lib is used with .net core, the resulting code will have the targeting implementation, so you'll be fine.

**Comment by alefcarlos** [comment]
@suvl , I'm sorry, I wasn't clear. Upgrading nuget packages from 2.1 to 3.1. Is that a option ?

**Comment by suvl** [comment]
@alefcarlos I don't think you got it. There is no `.NET Standard 3.1`, there is indeed `.NET Core 3.1` and the `.NET Standard` only goes up to v2.1.

.NET Standard is:
> Used for building libraries that can be referenced from all .NET implementations, such as .NET Framework, .NET Core and Xamarin.

[Check this](https://stackify.com/net-standard-explained/) to learn more about .NET Standard ;)

**Comment by alefcarlos** [comment]
@suvl , It was only a Nuget consolidate sugestion, for example [https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions/](Microsoft.Extensions.DependencyInjection.Abstractions/) has a 3.1 version which targets .NET Standard 2.0.

**Comment by suvl** [comment]
@alefcarlos that nuget you're referring to has `version` = 3.1 and targeting `netstandard20`. But we are not releasing any new feature, so we have no reason to up the `version` on our nuget. And we won't defl try to mimic the `netcore` version. We'll keep it independent on the `netcore` version and only worry about the `netstandard` version.
