### ISSUE TITLE
support dotnetcore3.1

### ISSUE THREAD

**Issue by wipxel** [nosinovacao/istio-tracing-aspnetcore#6]
Do you want me to send a PR for supporting dotnetcore3.1 ?

**Comment by calexandre** [comment]
@wipxel sure, we would be happy with your contribution :)

EDIT: Sorry @wipxel, but after looking into this, you don't need to update to dotnetcore3.1. This lib was built to support `netstandard20`. Please, take a look into #5 for more info.

Let us know if you have any issue.

**Comment by calexandre** [comment]
I'm going to close this.
Let us know if you have any issue.
